# Generated by Django 4.1.4 on 2022-12-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccgen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='design_id',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='download',
            old_name='design_id',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='download',
            old_name='user_id',
            new_name='user',
        ),
    ]
