# Generated by Django 4.1.4 on 2022-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccgen', '0004_alter_design_file_alter_download_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='time_of_download',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
