# Generated by Django 4.1.4 on 2022-12-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccgen', '0005_download_time_of_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='downloaded',
            field=models.CharField(choices=[('d', 'Downloaded'), ('u', 'Undownload'), ('s', 'Saved')], default='u', help_text='Downloaded?', max_length=1),
        ),
    ]
